// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqjaU7LsrL0SlWF7fzVM-Imxir7nhtM40',
    appId: '1:930580114832:web:8929f8853f79fd5f559715',
    messagingSenderId: '930580114832',
    projectId: 'project-omega-a8e0a',
    authDomain: 'project-omega-a8e0a.firebaseapp.com',
    storageBucket: 'project-omega-a8e0a.appspot.com',
    measurementId: 'G-D2GCJVH5YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOi2HR4kMvjZNM_mLCUjKPSFkCdhIjyg',
    appId: '1:930580114832:android:ddccc28f5ccfcb7c559715',
    messagingSenderId: '930580114832',
    projectId: 'project-omega-a8e0a',
    storageBucket: 'project-omega-a8e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAdZLtd3aw0GMqfD2xozJBFIkxXOoyuEs',
    appId: '1:930580114832:ios:e689955148e3f793559715',
    messagingSenderId: '930580114832',
    projectId: 'project-omega-a8e0a',
    storageBucket: 'project-omega-a8e0a.appspot.com',
    iosClientId: '930580114832-2udt1aq4k0o70r6t5lpemscsv9r169qk.apps.googleusercontent.com',
    iosBundleId: 'br.com.baz.projectOmega',
  );
}
